name = "r2-uploader-nano-banana-worker"
compatibility_date = "2023-12-01"

# modify `bucket_name`
# don't modify the `binding`
r2_buckets = [
    {binding = "R2_BUCKET", bucket_name = "nano-banana"}
]
